import type { Product, User } from "./types"

// Mock product data for development
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "smartphone",
    price: 999,
    originalPrice: 1099,
    image: "/iphone-15-pro-hands.png",
    images: ["/iphone-15-pro-front.png", "/iphone-15-pro-back.png", "/iphone-15-pro-side.png"],
    specifications: {
      brand: "Apple",
      model: "iPhone 15 Pro",
      color: "Natural Titanium",
      weight: "187g",
      dimensions: "146.6 × 70.6 × 8.25 mm",
      display: {
        size: '6.1"',
        resolution: "2556 × 1179",
        type: "Super Retina XDR OLED",
        refreshRate: "120Hz",
      },
      processor: "A17 Pro",
      ram: "8GB",
      storage: "128GB",
      battery: "3274 mAh",
      camera: {
        main: "48MP + 12MP + 12MP",
        front: "12MP",
        features: ["Night mode", "4K video", "Portrait mode"],
      },
      os: "iOS 17",
      connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "USB-C"],
    },
    score: 92,
    rating: 4.6,
    reviewCount: 1247,
    inStock: true,
    description: "The most advanced iPhone yet with titanium design and A17 Pro chip.",
    features: ["Titanium Design", "A17 Pro Chip", "Pro Camera System", "5G Ready"],
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "smartphone",
    price: 1199,
    image: "/samsung-galaxy-s24-ultra.png",
    images: ["/samsung-galaxy-s24-ultra-front.png", "/samsung-galaxy-s24-ultra-back.png"],
    specifications: {
      brand: "Samsung",
      model: "Galaxy S24 Ultra",
      color: "Titanium Black",
      weight: "232g",
      dimensions: "162.3 × 79.0 × 8.6 mm",
      display: {
        size: '6.8"',
        resolution: "3120 × 1440",
        type: "Dynamic AMOLED 2X",
        refreshRate: "120Hz",
      },
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB",
      battery: "5000 mAh",
      camera: {
        main: "200MP + 50MP + 12MP + 10MP",
        front: "12MP",
        features: ["Night mode", "8K video", "AI photography"],
      },
      os: "Android 14",
      connectivity: ["5G", "Wi-Fi 7", "Bluetooth 5.3", "USB-C"],
    },
    score: 94,
    rating: 4.7,
    reviewCount: 892,
    inStock: true,
    description: "Ultimate flagship with S Pen and advanced AI features.",
    features: ["S Pen Included", "AI Photography", "200MP Camera", "Titanium Build"],
    createdAt: new Date("2024-01-24"),
    updatedAt: new Date("2024-01-24"),
  },
  {
    id: "3",
    name: 'MacBook Pro 14"',
    brand: "Apple",
    category: "laptop",
    price: 1999,
    image: "/macbook-pro-14-inch.png",
    images: ["/macbook-pro-14-inch-open.png", "/macbook-pro-14-inch-closed.png"],
    specifications: {
      brand: "Apple",
      model: 'MacBook Pro 14"',
      color: "Space Gray",
      weight: "1.6kg",
      dimensions: "31.26 × 22.12 × 1.55 cm",
      cpu: "M3 Pro",
      ram: "18GB",
      storage: "512GB",
      storageType: "SSD",
      screenSize: '14.2"',
      display: {
        size: '14.2"',
        resolution: "3024 × 1964",
        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
      },
      battery: "70Wh",
      ports: ["3x Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3"],
      os: "macOS Sonoma",
    },
    score: 96,
    rating: 4.8,
    reviewCount: 543,
    inStock: true,
    description: "Professional laptop with M3 Pro chip for demanding workflows.",
    features: ["M3 Pro Chip", "Liquid Retina XDR", "All-day Battery", "Pro Connectivity"],
    createdAt: new Date("2023-10-30"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "headphones",
    price: 399,
    originalPrice: 449,
    image: "/sony-wh-1000xm5.png",
    images: ["/sony-wh-1000xm5-side-view.png", "/sony-wh-1000xm5-folded.png"],
    specifications: {
      brand: "Sony",
      model: "WH-1000XM5",
      color: "Black",
      weight: "250g",
      driverSize: "30mm",
      frequency: "4Hz - 40kHz",
      wireless: true,
      noiseCancellation: true,
      battery: "30 hours",
      connectivity: ["Bluetooth 5.2", "NFC", "3.5mm jack"],
    },
    score: 89,
    rating: 4.5,
    reviewCount: 2156,
    inStock: true,
    description: "Industry-leading noise canceling with premium sound quality.",
    features: ["Active Noise Canceling", "30hr Battery", "Quick Charge", "Multipoint Connection"],
    createdAt: new Date("2022-05-12"),
    updatedAt: new Date("2024-01-05"),
  },
]

export const mockUser: User = {
  id: "1",
  email: "user@example.com",
  name: "John Doe",
  preferences: {
    favoriteCategories: ["smartphone", "laptop"],
    priceRange: { min: 0, max: 2000 },
    preferredBrands: ["Apple", "Samsung"],
    notifications: true,
  },
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-15"),
}
